### PR TITLE
Update so it is compatible with Gradle 5.0

### PR DESCRIPTION
**Pull request by cmhdave**
Cleaned up this PR so the only thing that is changed is the upgrade to 5.0 and not the wrapper files

### CODE REVIEW

**Comment by alxndrsn** [comment]
What's the point of making it compatible with gradle 5 if the wrapper isn't updated?

**Comment by cmhdave** [comment]
I had a PR open for months that had the updated wrappers with no traction so I assumed it was because I updated the wrapper files too.  The last commit to the wrapper files was to downgrade the gradle version so I thought that was intentional and the goal was to allow the build to be compatible with gradle 1.  I would love for this fix to be pulled in as we're getting constant warnings in our build that the << operator is deprecated in gradle 5.0.  The best way I hoped for that to happen was to have the smallest PR possible.

**Comment by alxndrsn** [comment]
👍 yeah, it would be nice if someone could look at this.  Sadly I'm no longer a maintainer, but FWIW both PRs look fine to me.

**Comment by alxndrsn** [comment]
@thomasalanlee are you maintaining this project?

**Comment by willp-bl** [comment]
Thanks for sending this PR, but with the new changes here we wouldn't merge it now, so I'll close it.

We'll look at updating gradle when we can.

**Pull request closed without merging**
